# Generated by Django 3.1.6 on 2021-03-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeetContent',
            fields=[
                ('meet_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, default='', max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hostname', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('duration', models.CharField(blank=True, default='', max_length=20)),
                ('transcript', models.TextField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
