# Generated by Django 3.1.6 on 2021-02-26 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizer', '0003_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetcontent',
            name='content',
        ),
        migrations.AddField(
            model_name='meetcontent',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meetcontent',
            name='duration',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='meetcontent',
            name='hostname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='meetcontent',
            name='owner',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='meetcontent',
            name='summary',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='meetcontent',
            name='transcript',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='meetcontent',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
