# Generated by Django 3.1.6 on 2021-03-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizer', '0004_auto_20210226_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetcontent',
            name='duration',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='meetcontent',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='meetcontent',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='meetcontent',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='meetcontent',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='meetcontent',
            name='transcript',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
